site_name: MNRAS Template
site_description: A project template for writing papers to the MNRAS Journal
site_favicon: favicon.ico
repo_url: https://github.com/vcalderon2009/SDSS_ML_Groups_Paper_Overleaf_MNRAS
copyright: Project maintained <a href="http://vcalderon.me" target="_blank">Victor Calderon</a>.
google_analytics: ['UA-119772654-2', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
